install_vtas_varfile_filename: varfile
install_vtas_home_dir: /opt/vt
install_vtas_license_pathname: '{{ install_vtas_home_dir }}/vtmp/etc/vtlice.txt'
install_vtas_workdir: /opt/temp/vtas
install_vtas_base_dir: /usr/vtas_base
install_vtas_jdk_home: /usr/lib/jvm/java-1.11.0-openjdk-amd64

install_vtas_repository_host: localhost

install_vtas_archive: /tmp/vtas.zip
install_vtas_bin_archive_pathname: install/bin/VersaTestAS64.bin
install_vtas_license_archive_pathname: install/license/vtlice.txt
install_vtas_driver_archive_pathnames:
  - src: '{{ install_vtas_workdir }}/install/drivers/dfs.jar'
    dest: '{{ install_vtas_home_dir }}/var/fs/driverlib/local/com.ascert.driver.dfs-ver-1.9.23.jar'
  - src: '{{ install_vtas_workdir }}/install/drivers/dfs_gendrv_lib.jar'
    dest: '{{ install_vtas_home_dir }}/var/fs/driverlib/local/com.ascert.driver.dfsgendrvlib-ver-1.5.3.jar'
  - src: '{{ install_vtas_workdir }}/install/drivers/eftlib.jar'
    dest: '{{ install_vtas_home_dir }}/var/fs/driverlib/local/com.ascert.driver.eftlib-ver-0.9.9.jar'
  - src: '{{ install_vtas_workdir }}/install/drivers/mcbn_driver.jar'
    dest: '{{ install_vtas_home_dir }}/var/fs/driverlib/local/com.ascert.driver.mcbn-ver-1.9.0.jar'
  - src: '{{ install_vtas_workdir }}/install/drivers/com.ascert.driver.json-ver-1.1.0.jar'
    dest: '{{ install_vtas_home_dir }}/var/fs/driverlib/local/com.ascert.driver.json-ver-1.1.0.jar'
